services:
  postgresql:
    image: postgres:latest
    networks: [net]
    profiles:
      - dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USERNAME=user
      - POSTGRES_DB=postgres

networks:
  net: